-- MySQL Script generated by MySQL Workbench
-- Sat Apr 23 16:25:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `blog`;
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `approved` TINYINT NULL DEFAULT 0,
  `post` MEDIUMTEXT NOT NULL,
  `users_id` INT NOT NULL,
  `topic` VARCHAR(45) NOT NULL DEFAULT 'General',
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_posts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB AUTO_INCREMENT=50;


-- -----------------------------------------------------
-- Table `blog`.`posts_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`posts_has_tags` (
  `posts_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`posts_id`, `tags_id`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tags_id` ASC) VISIBLE,
  INDEX `fk_posts_has_tags_posts_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_has_tags_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `blog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `blog`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`users_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`users_has_roles` (
  `users_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `roles_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `blog`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tags (id,name) VALUES(1,"admin");
INSERT INTO tags (id,name) VALUES(2,"vender");
INSERT INTO tags (id,name) VALUES(3,"alert");
INSERT INTO tags (id,name) VALUES(4,"feedback");
INSERT INTO tags (id,name) VALUES(5,"aside");
INSERT INTO tags (id,name) VALUES(6,"timed");
INSERT INTO tags (name) VALUES("cool");
INSERT INTO tags (name) VALUES("car");
INSERT INTO tags (name) VALUES("space");
INSERT INTO tags (name) VALUES("unbelievable");
INSERT INTO tags (name) VALUES("beautiful");
INSERT INTO tags (name) VALUES("majestic");
INSERT INTO tags (name) VALUES("serene");

INSERT INTO roles (name) VALUES("admin");
INSERT INTO roles (name) VALUES("vender");
INSERT INTO roles (name) VALUES("marketer");

INSERT INTO users (name,password,email) VALUES("Sarah","pass","sadukie@email.com");
INSERT INTO users (name,password,email) VALUES("Joe","pass","joe@email.com");
INSERT INTO users (name,password,email) VALUES("Linda","pass","linda@email.com");
INSERT INTO users (name,password,email) VALUES("XYZMarketing","pass","xyz@email.com");

INSERT INTO users_has_roles (users_id,roles_id) VALUES(1,1);
INSERT INTO users_has_roles (users_id,roles_id) VALUES(2,2);
INSERT INTO users_has_roles (users_id,roles_id) VALUES(3,3);
INSERT INTO users_has_roles (users_id,roles_id) VALUES(4,2);
INSERT INTO users_has_roles (users_id,roles_id) VALUES(4,3);

INSERT INTO posts (users_id,approved,topic,post) VALUES(1,true,"Cool Car",'<p>here is an intiial line</p>
<p>here is a second line</p>
<p><img title="BBNsqzA.jpg" src="../images/2022/4/blobid1650831563182.jpg" alt="interesting" width="641" height="416" /></p>
<p>here is a closing line</p>');
INSERT INTO posts (users_id,approved,topic,post) VALUES(1,true,"Another test",'<p><img title="Nice View0.jpg" src="../images/2022/4/blobid1650928686859.jpg" alt="Scenery" width="800" height="500">Here is some text</p>
<p>&nbsp;</p>');
INSERT INTO posts (users_id,approved,topic,post) VALUES(1,true,"New Blog",'<h1>Hello World</h1>
<p>Check out the scenery</p>
<p><img title="landscape 12.jpg" src="../images/2022/4/blobid1650931954401.jpg" alt="no pic" width="600" height="338"></p>
<p>Quite the trail.</p>
<table style="border-collapse: collapse; width: 99.9667%;" border="1">
<tbody>
<tr>
<td style="width: 13.6096%;">&nbsp;</td>
<td style="width: 13.6096%;">col 1</td>
<td style="width: 13.6096%;">col 2</td>
<td style="width: 13.6096%;">col 3</td>
<td style="width: 13.6096%;">col 4</td>
<td style="width: 13.6096%;">col 5</td>
<td style="width: 13.6113%;">col 6</td>
</tr>
<tr>
<td style="width: 13.6096%;">row 1</td>
<td style="width: 13.6096%;">1</td>
<td style="width: 13.6096%;">2</td>
<td style="width: 13.6096%;">3</td>
<td style="width: 13.6096%;">4</td>
<td style="width: 13.6096%;">5</td>
<td style="width: 13.6113%;">6</td>
</tr>
<tr>
<td style="width: 13.6096%;">row 2</td>
<td style="width: 13.6096%;">12</td>
<td style="width: 13.6096%;">11</td>
<td style="width: 13.6096%;">10</td>
<td style="width: 13.6096%;">9</td>
<td style="width: 13.6096%;">8</td>
<td style="width: 13.6113%;">7</td>
</tr>
<tr>
<td style="width: 13.6096%;">row 3</td>
<td style="width: 13.6096%;">13</td>
<td style="width: 13.6096%;">14</td>
<td style="width: 13.6096%;">15</td>
<td style="width: 13.6096%;">16</td>
<td style="width: 13.6096%;">17</td>
<td style="width: 13.6113%;">18</td>
</tr>
</tbody>
</table>
<p><span style="font-family: Helvetica; font-size: 12px; background-color: #f8f9fa;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</span><br style="padding: 0px; margin: 0px; font-family: Helvetica; font-size: 12px; background-color: #f8f9fa;"><span style="font-family: Helvetica; font-size: 12px; background-color: #f8f9fa;">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</span></p>');
INSERT INTO posts (users_id,approved,topic,post) VALUES(1,true,"This is my title",'<h1>Disclaimer</h1>
<p>I know nothing</p>');

INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(1,50);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(1,51);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(2,53);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(2,54);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(2,55);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(3,55);
INSERT INTO posts_has_tags (posts_id,tags_id) VALUES(4,5);